openapi: 3.0.3
info:
  version: 1.0.0
  title: Bank Account API
  description: Bank Account API to retrieve bank account data
servers:
  - url: http://localhost:9999
    description: Developer server
tags:
  - name: bankAccounts
    description: methods that provide access to information and operations relating to bank accounts
paths:
  /accounts:
    get:
      tags:
        - bankAccounts
      summary: Find all bank accounts
      description: Find all bank accounts
      operationId: findBankAccounts
      responses:
        200:
          description: Bank accounts successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BankAccount'
        502:
          $ref: '#/components/responses/BadGateway'
  /accounts/{accountId}/withdrawal:
    post:
      tags:
        - bankAccounts
      summary: Withdraw money from account identified by id
      description: Withdraw money from account identified by id
      operationId: withdrawal
      parameters:
        - name: accountId
          in: path
          description: ID of account to return
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        description: withdrawal request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WithdrawRequest'
      responses:
        201:
          description: Withdraw successfully done
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        502:
          $ref: '#/components/responses/BadGateway'
  /accounts/{accountId}/deposit:
    post:
      tags:
        - bankAccounts
      summary: Deposit money from account identified by id
      description: Deposit money from account identified by id
      operationId: deposit
      parameters:
        - name: accountId
          in: path
          description: ID of account to return
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        description: deposit request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepositRequest'
      responses:
        201:
          description: Deposit successfully done
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        502:
          $ref: '#/components/responses/BadGateway'
  /accounts/{accountId}/transactions:
    get:
      tags:
        - bankAccounts
      summary: List all transactions of an account identified by its id
      description: List all transactions of an account identified by its id
      operationId: listTransactions
      parameters:
        - name: accountId
          in: path
          description: ID of account to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Transactions of an account retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTransactionsResponse'
        502:
          $ref: '#/components/responses/BadGateway'
  /accounts/{accountId}:
    get:
      tags:
        - bankAccounts
      summary: Find bank account by ID
      description: Return a specific bank account by its ID.
      operationId: findAccountById
      parameters:
        - name: accountId
          in: path
          description: ID of account to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Bank account successfully found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BankAccount'
        404:
          $ref: '#/components/responses/NotFound'
components:
  parameters:
    name:
      name: name
      in: path
      required: true
      schema:
        type: string
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadGateway:
      description: Bad Gateway error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    BankAccount:
      required:
        - id
        - balance
        - transactions
      properties:
        id:
          type: integer
          format: int64
          description: account id
        balance:
          type: number
          description: account balance
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
          description: account transactions history
    Transaction:
      required:
        - id
        - date
        - amount
        - transactionType
      properties:
        id:
          type: integer
          format: int64
          description: transaction id
        date:
          type: string
          format: date
        amount:
          type: number
          description: transaction amount
        transactionType:
          $ref: '#/components/schemas/TransactionType'
          description: transaction type
    TransactionType:
      type: string
      enum: [WITHDRAWAL, DEPOSIT]
      description: Type de transaction
    DepositRequest:
      required:
        - date
        - amount
      properties:
        date:
          type: string
          format: date
        amount:
          type: number
          description: deposit amount
    WithdrawRequest:
      required:
        - date
        - amount
      properties:
        date:
          type: string
          format: date
        amount:
          type: number
          description: withdrawal amount
    GetTransactionsResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
    Error:
      required:
        - code
        - type
        - message
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
